# Theme metadata
name = "new_theme"

# Is theme light or dark?
light = true

# Primary
primary = "#002D72"

# Menu
menu_primary = "#e21212"
menu_text = "#e21212"
menu_text_active = "#2962ff"
menu_title = "#2b2b2b"

# Home sections
home_section_odd = "rgb(255, 255, 255)"
home_section_even = "rgb(247, 247, 247)"
